spring:
  application:
    name: eureka_server

---
spring:
  profiles: eureka1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka1
    # 没有心跳的淘汰时间
    lease-expiration-duration-in-seconds: 10
    # 心跳间隔
    lease-renewal-interval-in-seconds: 5
  server:
    # 主动失效检测间隔
    eviction-interval-timer-in-ms: 5000
    # 自我保护模式，据说坑比较多
    enable-self-preservation: false
    # 心跳阈值计算周期
    renewal-threshold-update-interval-ms: 120000
    # 禁用readOnlyCacheMap
    use-read-only-response-cache: false
  client:
    service-url:
      defaultZone: http://eureka2:8762/eureka/

---
spring:
  profiles: eureka2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka2
    # 没有心跳的淘汰时间
    lease-expiration-duration-in-seconds: 10
    # 心跳间隔
    lease-renewal-interval-in-seconds: 5
  server:
    # 主动失效检测间隔
    eviction-interval-timer-in-ms: 5000
    # 自我保护模式，据说坑比较多
    enable-self-preservation: false
    # 心跳阈值计算周期
    renewal-threshold-update-interval-ms: 120000
    # 禁用readOnlyCacheMap
    use-read-only-response-cache: false
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/
